	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, YELLOW, YELLOW, YELLOW, GREEN, GREEN, GRAY
	tilepal 0, GRAY, GREEN, GREEN, GREEN, WATER, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GRAY, BROWN, BROWN, GRAY, GREEN, GRAY
	tilepal 0, GRAY, GRAY, GRAY, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, BROWN, BROWN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GRAY, BROWN, GREEN, GREEN, GREEN, RED
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, BROWN, BROWN, BROWN
	tilepal 0, GREEN, GREEN, GREEN, BROWN, GREEN, GREEN, GREEN, GREEN

rept 16
	db $ff
endr

	tilepal 1, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GREEN, RED, RED, GREEN, GRAY, GRAY
	tilepal 1, GRAY, GRAY, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GREEN, RED, RED, GREEN, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, BROWN, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, ROOF, ROOF, ROOF, ROOF
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY, GRAY
	tilepal 1, GRAY, GRAY, GRAY, GRAY, GREEN, TEXT, TEXT, TEXT
	tilepal 1, BROWN, BROWN, BROWN, GRAY, GRAY, GRAY, GRAY, GRAY
