	tilepal 0, GREEN, GREEN, GREEN, GREEN, BROWN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, RED, WATER, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, YELLOW, BROWN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, YELLOW, YELLOW, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, BROWN, GREEN
	tilepal 0, GREEN, GRAY, GRAY, GREEN, RED, RED, RED, RED
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GRAY, BROWN, GRAY, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GRAY, GRAY, GRAY, TEXT

rept 16
	db $ff
endr

	tilepal 1, ROOF, ROOF, ROOF, ROOF, TEXT, TEXT, TEXT, TEXT
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 1, ROOF, ROOF, ROOF, ROOF
