	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GRAY, GRAY, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GRAY, GRAY, GRAY, GRAY, GREEN, GREEN
	tilepal 0, GREEN, YELLOW, YELLOW, GRAY, GRAY, GREEN, GREEN, GREEN
	tilepal 0, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN, GREEN
	tilepal 0, GREEN, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT, TEXT
	tilepal 0, TEXT, TEXT, TEXT, TEXT, TEXT, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, TEXT
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 0, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF

rept 16
	db $ff
endr

	tilepal 1, TEXT, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, TEXT, TEXT, ROOF, ROOF, ROOF, ROOF, ROOF, TEXT
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, TEXT, TEXT, TEXT, TEXT, TEXT, ROOF, ROOF, ROOF
	tilepal 1, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, TEXT, TEXT, TEXT, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, TEXT, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF, ROOF
	tilepal 1, TEXT, TEXT, TEXT, ROOF, ROOF, ROOF, ROOF, ROOF
